include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - '**/*.gen.dart'

  errors:
    prefer_const_constructors: warning
    unused_import: error
    unnecessary_import: error
    invalid_annotation_target: ignore

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    omit_local_variable_types: true
    lines_longer_than_80_chars: false
    import_of_legacy_library_into_null_safe: false
    sort_pub_dependencies: false
    avoid_positional_boolean_parameters: false
    directives_ordering: false
    use_key_in_widget_constructors: false
    parameter_assignments: true
    avoid_web_libraries_in_flutter: false
