name: website
description: website

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^1.0.4
  google_fonts: ^2.0.0
  cupertino_icons: ^1.0.2
  gap: ^2.0.0
  flutter_hooks: ^0.18.1
  font_awesome_flutter: ^9.2.0
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter:
  assets:
    - assets/images/
  uses-material-design: true

flutter_gen:
  integrations:
    flutter_svg: true
